
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'OBJETODIRECTO SUJETO VERBOPRESENTE\n    oracion : palabra \n            | palabra oracion\n    \n    palabra : SUJETO \n            | VERBOPRESENTE\n            | OBJETODIRECTO\n    \n    oracion : VERBOPRESENTE SUJETO OBJETODIRECTO\n            | VERBOPRESENTE OBJETODIRECTO SUJETO\n            | SUJETO OBJETODIRECTO VERBOPRESENTE\n            | OBJETODIRECTO VERBOPRESENTE SUJETO\n            | OBJETODIRECTO SUJETO VERBOPRESENTE\n    \n    oracion : SUJETO VERBOPRESENTE OBJETODIRECTO\n    '
    
_lr_action_items = {'VERBOPRESENTE':([0,2,3,4,5,9,12,],[3,3,-4,10,11,15,18,]),'SUJETO':([0,2,3,4,5,8,11,],[4,4,7,-3,12,14,17,]),'OBJETODIRECTO':([0,2,3,4,5,7,10,],[5,5,8,9,-5,13,16,]),'$end':([1,2,3,4,5,6,13,14,15,16,17,18,],[0,-1,-4,-3,-5,-2,-6,-7,-8,-11,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'oracion':([0,2,],[1,6,]),'palabra':([0,2,],[2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> oracion","S'",1,None,None,None),
  ('oracion -> palabra','oracion',1,'p_oracion','parser.py',10),
  ('oracion -> palabra oracion','oracion',2,'p_oracion','parser.py',11),
  ('palabra -> SUJETO','palabra',1,'p_palabra','parser.py',17),
  ('palabra -> VERBOPRESENTE','palabra',1,'p_palabra','parser.py',18),
  ('palabra -> OBJETODIRECTO','palabra',1,'p_palabra','parser.py',19),
  ('oracion -> VERBOPRESENTE SUJETO OBJETODIRECTO','oracion',3,'p_oracionin','parser.py',25),
  ('oracion -> VERBOPRESENTE OBJETODIRECTO SUJETO','oracion',3,'p_oracionin','parser.py',26),
  ('oracion -> SUJETO OBJETODIRECTO VERBOPRESENTE','oracion',3,'p_oracionin','parser.py',27),
  ('oracion -> OBJETODIRECTO VERBOPRESENTE SUJETO','oracion',3,'p_oracionin','parser.py',28),
  ('oracion -> OBJETODIRECTO SUJETO VERBOPRESENTE','oracion',3,'p_oracionin','parser.py',29),
  ('oracion -> SUJETO VERBOPRESENTE OBJETODIRECTO','oracion',3,'p_oracionc','parser.py',37),
]
